# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build -x test
      
      
    - name: Docker build and push to docker hub
      run: |
        docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }} 
        docker build -t kpp-gateway . 
        docker tag kpp-gateway ${{ secrets.DOCKER_ID }}/kpp-gateway:${GITHUB_SHA::7} 
        docker push ${{ secrets.DOCKER_ID }}/kpp-gateway:${GITHUB_SHA::7}
    
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@master
      with:
        host: ec2-15-164-212-128.ap-northeast-2.compute.amazonaws.com
        username: ec2-user
        key: ${{ secrets.AWS_PEM }}
        envs: GITHUB_SHA
        script: |
          docker pull ${{ secrets.DOCKER_ID }}/kpp-gateway:${GITHUB_SHA::7}
          docker tag ${{ secrets.DOCKER_ID }}/kpp-gateway:${GITHUB_SHA::7} kpp-gateway
          docker stop kpp-gateway || true
          docker run -d --rm --name kpp-gateway --network kpp kpp-gateway
